//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorLoggerWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long Id { get; set; }
        public System.DateTime LogDate { get; set; }
        public int ApplicationId { get; set; }
        public string Url { get; set; }
        public string ModuleName { get; set; }
        public string FileName { get; set; }
        public string MethodName { get; set; }
        public string ErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public bool IsEmailSent { get; set; }
    }
}
